### ISSUE TITLE
스페이스 생성/참가 개발[space]

### ISSUE THREAD

**Issue by soosungp33** [dnd-side-project/dnd-5th-8-backend#1]
## 😊 이슈 내용
- Service단 : SpaceService 추가
- Domain단 : Space 추가
- Controller단 : SpaceController 추가
- Dto단 : SpaceDto 추가

### 1️⃣ 생성
- POST
- api : /space/create
- 형식 : JSON
- request : 
```
{
   id : long
   name : String
}
```
- response : 
```
String(code)
```

### 2️⃣ 참가
- GET
- api : /space/attend/ + {code}
- 형식 : JSON
- request : 없음
- response : 
```
{
   spaceName : String
   userCount : Int
   isExist : Bool
   roomMaster : String
   family : List
}
```

- PUT
- api: /space/attend/ + {id}
- 형식 : JSON
- request : 
```
{
    code : String
}
```
- response : -> 굳이 안받아도 됨(그냥 확인 작업)
```
long(space_id)
```

**Comment by 2o1da** [comment]
1. 생성에서 request 타입이 form-data가 아니라 JSON 인 것 같습니다!
